# Generated by Django 2.2.1 on 2019-05-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourses',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentcourses',
            name='course',
            field=models.ForeignKey(default=2, on_delete=True, to='courses.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentcourses',
            name='student',
            field=models.ForeignKey(on_delete=True, to='students.Student'),
        ),
    ]
